
import java.awt.Color;
import java.awt.GridLayout;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class Frm_Details extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Details
     */
    private String username , password , firstname , lastname , address ,gender, skills,specialization; 
    public Frm_Details() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSpecial = new javax.swing.ButtonGroup();
        txtLastname = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        rbjava = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        rbPython = new javax.swing.JRadioButton();
        cmbGender = new javax.swing.JComboBox<>();
        chk3 = new javax.swing.JCheckBox();
        chk1 = new javax.swing.JCheckBox();
        chk4 = new javax.swing.JCheckBox();
        chk2 = new javax.swing.JCheckBox();
        txtAddress = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtFirstname = new javax.swing.JTextField();
        btnChange = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtLastname.setFont(new java.awt.Font("sansserif", 2, 12)); // NOI18N
        txtLastname.setForeground(new java.awt.Color(204, 204, 204));
        txtLastname.setText("lastname");
        txtLastname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLastnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLastnameFocusLost(evt);
            }
        });

        txtPass.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        txtPass.setText("password");
        txtPass.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtPass.setEnabled(false);
        txtPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPassFocusLost(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("User Details");

        btnSave.setBackground(new java.awt.Color(0, 153, 255));
        btnSave.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 51, 51));
        jLabel12.setText("*");

        jLabel14.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 51, 51));
        jLabel14.setText("*");

        jLabel9.setText("Specialization:");

        jLabel15.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 51, 51));
        jLabel15.setText("*");

        btnSpecial.add(rbjava);
        rbjava.setText("Java");

        jLabel16.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 51, 51));
        jLabel16.setText("*");

        btnSpecial.add(rbPython);
        rbPython.setText("Python");

        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));
        cmbGender.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        chk3.setText("Team Lead");

        chk1.setText("Programming");

        chk4.setText("UI/UX Design");

        chk2.setText("Visual Graphics");

        txtAddress.setFont(new java.awt.Font("sansserif", 2, 12)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(204, 204, 204));
        txtAddress.setText("address");
        txtAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAddressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAddressFocusLost(evt);
            }
        });

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        jLabel4.setText("Last name:");

        jLabel5.setText("First name:");

        jLabel6.setText("Address:");

        jLabel7.setText("Gender:");

        jLabel8.setText("Skills:");

        txtUsername.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        txtUsername.setText("username");
        txtUsername.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtUsername.setEnabled(false);
        txtUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsernameFocusLost(evt);
            }
        });

        txtFirstname.setFont(new java.awt.Font("sansserif", 2, 12)); // NOI18N
        txtFirstname.setForeground(new java.awt.Color(204, 204, 204));
        txtFirstname.setText("firstname");
        txtFirstname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFirstnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFirstnameFocusLost(evt);
            }
        });

        btnChange.setText("change");
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(102, 204, 255));
        btnBack.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel1)
                        .addGap(16, 16, 16)
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel2)
                        .addGap(20, 20, 20)
                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(btnChange))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel5)
                        .addGap(12, 12, 12)
                        .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel4)
                        .addGap(13, 13, 13)
                        .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel6)
                        .addGap(12, 12, 12)
                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel16))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel7)
                        .addGap(13, 13, 13)
                        .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(chk1)
                        .addGap(6, 6, 6)
                        .addComponent(chk2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(chk3)
                        .addGap(18, 18, 18)
                        .addComponent(chk4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel9)
                        .addGap(12, 12, 12)
                        .addComponent(rbjava)
                        .addGap(32, 32, 32)
                        .addComponent(rbPython))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel10)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel12))))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChange))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel15)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel16))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel7))
                    .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel8))
                    .addComponent(chk1)
                    .addComponent(chk2))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chk3)
                    .addComponent(chk4))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel9))
                    .addComponent(rbjava)
                    .addComponent(rbPython))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void setData(String user) throws IOException{
    
         File f = new File(user +".txt");
        try {
            BufferedReader reader = new BufferedReader(new FileReader(f));
                        int count = 0;
                        
                        String line;
                        while ((line = reader.readLine()) != null) {
                            if(count == 0){
                                   txtUsername.setText(line);
                                   this.username = line;
                            }
                            if(count == 1 ){
                                   txtPass.setText(line);
                                   this.password = line;
                            }
                            if(count == 2){
                                   txtFirstname.setText(line);
                                   this.firstname = line;
                            }
                            if(count == 3){
                                   txtLastname.setText(line);
                                   this.lastname = line;
                            }
                            if(count == 4){
                                   txtAddress.setText(line);
                                   this.address = line;
                            }
                            if(count == 5){
                                   cmbGender.setSelectedItem(line);
                                   this.gender = line;
                            }
                            if(count == 6){
                                   String[] values = line.split(",");
                                   this.skills = line;
                                   for (String value : values) {
                                        if(value.equals("Programming")){
                                            chk1.setSelected(true);
                                        }
                                        if(value.equals("Visual Graphics")){
                                            chk2.setSelected(true);
                                        }
                                        if(value.equals("Team Lead")){
                                            chk3.setSelected(true);
                                        }
                                        if(value.equals("UI/UX Design")){
                                            chk4.setSelected(true);
                                        }
                                    }
                            }
                            if(count == 7){
                                    this.specialization = line;
                                    if(line.equals("Java")){
                                        rbjava.setSelected(true);
                                    }
                                    if(line.equals("Python")){
                                        rbPython.setSelected(true);
                                    }
                            }
                            count++;
                        }
                        reader.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Frm_Details.class.getName()).log(Level.SEVERE, null, ex);
        }
                   
    }
    private void txtLastnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLastnameFocusGained
        // TODO add your handling code here:
        txtLastname.setForeground(Color.black);
        txtLastname.selectAll();
    }//GEN-LAST:event_txtLastnameFocusGained

    private void txtLastnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLastnameFocusLost
        // TODO add your handling code here:
        String last = txtLastname.getText().trim();
        if(last.isEmpty()){
            txtLastname.setForeground(Color.LIGHT_GRAY);
            txtLastname.setText("lastname");
        }
    }//GEN-LAST:event_txtLastnameFocusLost

    private void txtPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassFocusGained
        // TODO add your handling code here:
        txtPass.setForeground(Color.black);
        txtPass.selectAll();
        
    }//GEN-LAST:event_txtPassFocusGained

    private void txtPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassFocusLost
        // TODO add your handling code here:
        char [] pass = txtPass.getPassword();
        if(pass.length == 0){
            txtPass.setForeground(Color.LIGHT_GRAY);
            txtPass.setText("password");
            txtPass.setEchoChar((char)0);
        }

    }//GEN-LAST:event_txtPassFocusLost

    private void txtAddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAddressFocusGained
        // TODO add your handling code here:
        txtAddress.setForeground(Color.black);
        txtAddress.selectAll();
    }//GEN-LAST:event_txtAddressFocusGained

    private void txtAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAddressFocusLost
        // TODO add your handling code here:
        String address = txtAddress.getText().trim();
        if(address.isEmpty()){
            txtAddress.setForeground(Color.LIGHT_GRAY);
            txtAddress.setText("address");
        }
    }//GEN-LAST:event_txtAddressFocusLost

    private void txtUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusGained
        // TODO add your handling code here:
        txtUsername.setForeground(Color.black);
        txtUsername.selectAll();
    }//GEN-LAST:event_txtUsernameFocusGained

    private void txtUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusLost
        // TODO add your handling code here:
        String user = txtUsername.getText().trim();
        if(user.isEmpty()){
            txtUsername.setForeground(Color.LIGHT_GRAY);
            txtUsername.setText("username");
        }

    }//GEN-LAST:event_txtUsernameFocusLost

    private void txtFirstnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFirstnameFocusGained
        // TODO add your handling code here:
        txtFirstname.setForeground(Color.black);
        txtFirstname.selectAll();
    }//GEN-LAST:event_txtFirstnameFocusGained

    private void txtFirstnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFirstnameFocusLost
        // TODO add your handling code here:
        String first = txtFirstname.getText().trim();
        if(first.isEmpty()){
            txtFirstname.setForeground(Color.LIGHT_GRAY);
            txtFirstname.setText("firstname");
        }
    }//GEN-LAST:event_txtFirstnameFocusLost

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        // TODO add your handling code here:
        JPanel panel = new JPanel();
        JPasswordField field1 = new JPasswordField(10);
        JPasswordField field2 = new JPasswordField(10);
        JPasswordField field3 = new JPasswordField(10);

        panel.setLayout(new GridLayout(3, 2));
        panel.add(new JLabel("Old Password"));
        panel.add(field1);
        panel.add(new JLabel("New Password"));
        panel.add(field2);
        panel.add(new JLabel("Confirm New Password"));
        panel.add(field3);

        // Show the option pane with the panel
        int result = JOptionPane.showConfirmDialog(
                null,
                panel,
                "Enter values:",
                JOptionPane.OK_CANCEL_OPTION
        );

        // Check the user's choice
        if (result == JOptionPane.OK_OPTION) {
            // User clicked OK, retrieve the values
            String oldP = new String(field1.getPassword());
            String newP = new String(field2.getPassword());
            String newP2 = new String(field3.getPassword());
            
            if(oldP.equals(this.password)){
                
                if(newP.equals(newP2)){
                    
                    if(newP.equals(this.password)){
                        JOptionPane.showMessageDialog(null,"Old Password cannot be a new Password");
                    }else{
                        this.password = newP;
                        updateData();
                        JOptionPane.showMessageDialog(null,"Password Successfully Changed!");
                    }
                }else{
                    JOptionPane.showMessageDialog(null,"Password Mismatch!");
                }
            }else{
                JOptionPane.showMessageDialog(null,"Old Password does not match!");
            }
            
        } else {
            // User clicked Cancel or closed the dialog
            System.out.println("User canceled the input.");
        }

        // Check the user's choice
       
    }//GEN-LAST:event_btnChangeActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        System.out.println("Click Button");
        System.out.println(this.username+".txt");
        int skillCount = 0;
        String cFirst = txtFirstname.getText();
        String cLast = txtLastname.getText();
        String cAdd = txtAddress.getText();
        String cGender = cmbGender.getSelectedItem().toString();
        String xSkills [] = new String [4];
        if(chk1.isSelected()){
            xSkills[skillCount] = "Programming";
            skillCount++;
        }
        if(chk2.isSelected()){
            xSkills[skillCount] = "Visual Graphics";
            skillCount++;
        }
        if(chk3.isSelected()){
            xSkills[skillCount] = "Team Lead";
            skillCount++;
        }
        if(chk4.isSelected()){
            xSkills[skillCount] = "UI/UX Design";
            skillCount++;
        }
        String cSkill = "";
        for (int x = 0 ; x < skillCount;x++){
            cSkill += xSkills[x] + ",";
        }
        
        String cSpecial = "";
        if(rbjava.isSelected()){
            cSpecial = "Java";
        }
        if(rbPython.isSelected()){
            cSpecial = "Python";
        }
        
        
        try {
            FileWriter writer = new FileWriter(this.username+".txt");
            writer.write(username);
            writer.write("\n");
            writer.write(password);
            writer.write("\n");
            writer.write(cFirst);
            writer.write("\n");
            writer.write(cLast);
            writer.write("\n");
            writer.write(cAdd);
            writer.write("\n");
            writer.write(cGender);
            writer.write("\n");
            writer.write(cSkill);
            writer.write("\n");
            writer.write(cSpecial);
            writer.write("\n");


            writer.close();
            JOptionPane.showMessageDialog(null, "Saved Successfully");
        } catch (IOException ex) {
            Logger.getLogger(Frm_Details.class.getName()).log(Level.SEVERE, null, ex);
        }
                            
    }//GEN-LAST:event_btnSaveActionPerformed
    
    private void updateData(){
                            FileWriter writer;
        try {
            writer = new FileWriter(username+".txt");
            writer.write(username);
                            writer.write("\n");
                            writer.write(password);
                            writer.write("\n");
                            writer.write(firstname);
                            writer.write("\n");
                            writer.write(lastname);
                            writer.write("\n");
                            writer.write(address);
                            writer.write("\n");
                            writer.write(gender);
                            writer.write("\n");
                            writer.write(skills);
                            writer.write("\n");
                            writer.write(specialization);
                            writer.write("\n");


                            writer.close();
        } catch (IOException ex) {
            Logger.getLogger(Frm_Details.class.getName()).log(Level.SEVERE, null, ex);
        }
                            
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup btnSpecial;
    private javax.swing.JCheckBox chk1;
    private javax.swing.JCheckBox chk2;
    private javax.swing.JCheckBox chk3;
    private javax.swing.JCheckBox chk4;
    private javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rbPython;
    private javax.swing.JRadioButton rbjava;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
